/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Page1RouteImport } from './routes/page-1'
import { Route as Page0RouteImport } from './routes/page-0'
import { Route as IndexRouteImport } from './routes/index'

const Page1Route = Page1RouteImport.update({
  id: '/page-1',
  path: '/page-1',
  getParentRoute: () => rootRouteImport,
} as any)
const Page0Route = Page0RouteImport.update({
  id: '/page-0',
  path: '/page-0',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page-0': typeof Page0Route
  '/page-1': typeof Page1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page-0': typeof Page0Route
  '/page-1': typeof Page1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/page-0': typeof Page0Route
  '/page-1': typeof Page1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page-0' | '/page-1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page-0' | '/page-1'
  id: '__root__' | '/' | '/page-0' | '/page-1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Page0Route: typeof Page0Route
  Page1Route: typeof Page1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page-1': {
      id: '/page-1'
      path: '/page-1'
      fullPath: '/page-1'
      preLoaderRoute: typeof Page1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-0': {
      id: '/page-0'
      path: '/page-0'
      fullPath: '/page-0'
      preLoaderRoute: typeof Page0RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Page0Route: Page0Route,
  Page1Route: Page1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
