/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermsAndConditionsImport } from './routes/terms-and-conditions'
import { Route as Page1Import } from './routes/page-1'
import { Route as Page0Import } from './routes/page-0'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TermsAndConditionsRoute = TermsAndConditionsImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRoute,
} as any)

const Page1Route = Page1Import.update({
  id: '/page-1',
  path: '/page-1',
  getParentRoute: () => rootRoute,
} as any)

const Page0Route = Page0Import.update({
  id: '/page-0',
  path: '/page-0',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/page-0': {
      id: '/page-0'
      path: '/page-0'
      fullPath: '/page-0'
      preLoaderRoute: typeof Page0Import
      parentRoute: typeof rootRoute
    }
    '/page-1': {
      id: '/page-1'
      path: '/page-1'
      fullPath: '/page-1'
      preLoaderRoute: typeof Page1Import
      parentRoute: typeof rootRoute
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page-0': typeof Page0Route
  '/page-1': typeof Page1Route
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page-0': typeof Page0Route
  '/page-1': typeof Page1Route
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/page-0': typeof Page0Route
  '/page-1': typeof Page1Route
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page-0' | '/page-1' | '/terms-and-conditions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page-0' | '/page-1' | '/terms-and-conditions'
  id: '__root__' | '/' | '/page-0' | '/page-1' | '/terms-and-conditions'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Page0Route: typeof Page0Route
  Page1Route: typeof Page1Route
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Page0Route: Page0Route,
  Page1Route: Page1Route,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/page-0",
        "/page-1",
        "/terms-and-conditions"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/page-0": {
      "filePath": "page-0.tsx"
    },
    "/page-1": {
      "filePath": "page-1.tsx"
    },
    "/terms-and-conditions": {
      "filePath": "terms-and-conditions.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
